LibraryProject/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryProject.Models
{
    public class Message
    {
        [Key]
        [Display(Name = "Mesaj No")]
        public int Id { get; set; }

        public string Title { get; set; }

        public string Content { get; set; }

        public string AttachmentUrl { get; set; }

        [Display(Name = "Gönderim Tarihi")]
        public DateTime CreatedDate { get; set; }

        public bool IsRead { get; set; }

        public bool IsDraft { get; set; }

        public string SenderId { get; set; }
        public LibraryUser Sender { get; set; }

        public string ReceiverId { get; set; }
        public LibraryUser Receiver { get; set; }
    }
}

LibraryProject/Models/MessageDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryProject.Models
{
    public class MessageDetail
    {
        public Message Message { get; set; }
        public LibraryUser User { get; set; }
        public bool IsCurrentUserSender { get; set; }
    }
}

LibraryProject/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LibraryProject.Data;
using LibraryProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LibraryProject.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<LibraryUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IHostingEnvironment _hostingEnvironment;

        public MessagesController(ApplicationDbContext context, UserManager<LibraryUser> userManager, RoleManager<IdentityRole> roleManager, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Inbox()
        {
            var userEmail = User.Identity.Name;
            var userId = _context.Users.Where(u => u.Email == userEmail).FirstOrDefault().Id;

            var inboxMessages = _context.Messages.Where(m => m.ReceiverId == userId).Include(m => m.Sender).OrderByDescending(m => m.CreatedDate).ToList();

            return View(inboxMessages);
        }

        public IActionResult Sent()
        {
            var userEmail = User.Identity.Name;
            var userId = _context.Users.Where(u => u.Email == userEmail).FirstOrDefault().Id;

            var sentMessages = _context.Messages.Where(m => m.SenderId == userId).Include(m => m.Receiver).OrderByDescending(m => m.CreatedDate).ToList();

            return View(sentMessages);
        }

        public IActionResult ComposeMessage(string Id)
        {
            var message = new Message();

            if (!String.IsNullOrEmpty(Id))
            {
                message.ReceiverId = Id;
            }

            var userEmail = User.Identity.Name;
            var userId = _context.Users.Where(u => u.Email == userEmail).FirstOrDefault().Id;

            var allUsers = _context.Users.ToList();

            var userList = new List<UserViewModel>();

            foreach (var user in allUsers)
            {
                var userData = new UserViewModel() { FullName = user.FirstName + " " + user.LastName, Id = user.Id };
                userList.Add(userData);
            }

            ViewData["ReceiverId"] = new SelectList(userList, "Id", "FullName");

            return View(message);
        }

        [HttpPost]
        public async Task<IActionResult> ComposeMessage([Bind("Title,Content,ReceiverId")] Message message, IFormFile attachmentFile)
        {
            var userEmail = User.Identity.Name;
            var userId = _context.Users.Where(u => u.Email == userEmail).FirstOrDefault().Id;

            if (String.IsNullOrEmpty(message.Title) || String.IsNullOrEmpty(message.Content) || String.IsNullOrEmpty(message.ReceiverId) || message.ReceiverId == userId)
            {
                ModelState.AddModelError(string.Empty, "Lütfen içeriği düzenleyiniz.");

                if(message.ReceiverId == userId)
                {
                    ModelState.AddModelError(string.Empty, "Kendinize mesaj gönderemezsiniz.");
                }

                var allUsers = _context.Users.ToList();

                var userList = new List<UserViewModel>();

                foreach (var user in allUsers)
                {
                    var userData = new UserViewModel() { FullName = user.FirstName + " " + user.LastName, Id = user.Id };
                    userList.Add(userData);
                }

                ViewData["ReceiverId"] = new SelectList(userList, "Id", "FullName");

                return View();
            }
            else
            {
                // File upload from cetstore project
                if (attachmentFile != null)
                {
                    string dirPath = Path.Combine(_hostingEnvironment.WebRootPath, @"uploads\");
                    var fileName = Guid.NewGuid().ToString().Replace("-", "") + "_" + attachmentFile.FileName;
                    using (var fileStream = new FileStream(dirPath + fileName, FileMode.Create))
                    {
                        await attachmentFile.CopyToAsync(fileStream);
                    }

                    message.AttachmentUrl = fileName;
                }
                
                message.CreatedDate = DateTime.Now;
                message.SenderId = userId;
                message.IsDraft = false;
                message.IsRead = false;

                _context.Messages.Add(message);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("Sent");
        }

        public IActionResult MessageDetail(int id)
        {
            var message = _context.Messages.Where(m => m.Id == id).Include(m => m.Sender).Include(m => m.Receiver).FirstOrDefault();

            if(message == null)
            {
                return NotFound();
            }

            var messageDetail = new MessageDetail();

            var userEmail = User.Identity.Name;
            var userId = _context.Users.Where(u => u.Email == userEmail).FirstOrDefault().Id;

            messageDetail.Message = message;

            if (message.SenderId == userId)
            {
                messageDetail.User = message.Receiver;
                messageDetail.IsCurrentUserSender = true;
            }
            else if(message.ReceiverId == userId)
            {
                messageDetail.User = message.Sender;
                messageDetail.IsCurrentUserSender = false;
            }
            else
            {
                return NotFound();
            }

            return View(messageDetail);
        }

        //[HttpGet]
        //public IActionResult DownloadAttachment(string id)
        //{
        //    //var net = new System.Net.WebClient();
        //    //id = "/uploads/" + id;
        //    //var data = net.DownloadData(id);
        //    //var content = new System.IO.MemoryStream(data);
        //    //var contentType = "APPLICATION/octet-stream";
        //    //var fileName = "something.bin";
        //    //return File(content, contentType, fileName);

        //    string dirPath = Path.Combine(_hostingEnvironment.WebRootPath, @"uploads\");
        //    var memory = new MemoryStream();
        //    using (var stream = new FileStream(path, FileMode.Open))
        //    {
        //        await stream.CopyToAsync(memory);
        //    }
        //    memory.Position = 0;
        //    return File(memory, GetContentType(path), Path.GetFileName(path));
        //}
    }
}

LibraryProject/Views/Messages/ComposeMessage.cshtml
@model Message
@{
    ViewData["Title"] = "ComposeMessage";
    Layout = "~/Views/Shared/_LayoutMessages.cshtml";
}

<div class="col-sm-9">
    <section class="panel">
        <header class="panel-heading wht-bg">
            <h4 class="gen-case">
                Yeni Mesaj
            </h4>
        </header>
        <div class="panel-body">
            <div class="compose-mail">
                <form role="form-horizontal" method="post" action="ComposeMessage" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group" style="margin-bottom: 5px;">
                        <label for="ReceiverId" class="control-label">Kime:</label>
                        @*@Html.DropDownList("ReceiverId", ViewBag.ReceiverId, "Seçiniz", new { @class = "form-control" })*@
                        <select asp-for="ReceiverId" class="form-control" style="display:inline-block;width:90%;padding: 6px 7px;" asp-items="ViewBag.ReceiverId">
                            <option disabled selected> Kişi Seçiniz </option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="Title" class="">Başlık:</label>
                        <input asp-for="Title" class="form-control" style="width:90%;border: 1px solid #ccc;padding:6px 12px;" />
                    </div>
                    <div class="form-group">
                        <label for="Content">Mesaj:</label>
                        <textarea cols="40" rows="5" name="Content" id="Content" class="default form-control" style="width:90%;"></textarea>
                    </div>
                    <div class="form-group">
                        <label class="control-label"> Ek: </label>
                        <input type="file" id="attachmentFile" name="attachmentFile" />
                    </div>
                    <div class="compose-btn">
                        <button class="btn btn-theme btn-sm" type="submit"><i class="fa fa-check"></i> Gönder </button>
                        <a asp-controller="Messages" asp-action="Inbox" class="btn btn-sm btn-danger"><i class="fa fa-times"></i> İptal </a>
                        @*<button class="btn btn-sm"><i class="fa fa-times"></i> Discard</button>*@
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>

LibraryProject/Views/Messages/Inbox.cshtml
@model List<Message>

@{
    ViewData["Title"] = "Gelen Mesajlarım";
    Layout = "~/Views/Shared/_LayoutMessages.cshtml";
}

<div class="col-sm-9">
    <section class="panel">
        <header class="panel-heading wht-bg">
            <h4 class="gen-case">
                Gelen Mesajlar
            </h4>
        </header>
        <div class="panel-body minimal">
            <div class="table-inbox-wrap ">
                <table class="table table-inbox table-hover">
                    <thead>
                        <tr>
                            <th style="width: 200px;">Kime</th>
                            <th style="width: 400px;">Başlık</th>
                            <th class="text-right">Gönderilme Tarihi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var message in Model)
                        {
                            <tr class="">
                                <td style="width: 200px;" class="view-message dont-show">@message.Sender.FirstName @message.Sender.LastName</td>
                                <td style="width: 400px;" class="view-message view-message">@message.Title</td>
                                <td class="view-message text-right">@message.CreatedDate</td>
                                <td><a asp-controller="Messages" asp-action="MessageDetail" asp-route-id="@message.Id" class="btn btn-primary btn-xs" style="color: #fff;">Detaylar </a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>

LibraryProject/Views/Messages/MessageDetail.cshtml
@model MessageDetail

@{
    ViewData["Title"] = "Mesaj Detayları";
    Layout = "~/Views/Shared/_LayoutMessages.cshtml";
}

<div class="col-sm-9">
    <section class="panel">
        <header class="panel-heading wht-bg">
            @if (Model.IsCurrentUserSender)
            {
                <h4 class="gen-case">
                    Mesaj Detayları (Gönderilen Mesaj)
                </h4>
            }
            else
            {
                <h4 class="gen-case">
                    Mesaj Detayları (Gelen Mesaj)
                </h4>
            }
        </header>
        <div class="panel-body ">
            <div class="mail-header row">
                <div class="col-md-8">
                    <h4 class="pull-left"> @Model.Message.Title </h4>
                </div>
                <div class="col-md-4">
                    <div class="compose-btn pull-right">
                        <a asp-controller="Messages" asp-action="ComposeMessage" asp-route-id="@Model.User.Id" class="btn btn-sm btn-theme"><i class="fa fa-reply"></i> Yanıtla </a>
                    </div>
                </div>
            </div>
            <div class="mail-sender">
                <div class="row">
                    <div class="col-md-8">
                        <img src="~/uploads/@Model.User.PhotoUrl" alt="">
                        <strong> @Model.User.FirstName @Model.User.LastName </strong> | 
                        <span> @Model.User.Email </span>
                    </div>
                    <div class="col-md-4">
                        <p class="date"> @Model.Message.CreatedDate </p>
                    </div>
                </div>
            </div>
            <div class="view-mail">
                <p>
                    @Model.Message.Content
                </p>
            </div>
            <div class="attachment-mail">
                @if (!String.IsNullOrEmpty(Model.Message.AttachmentUrl))
                {
                    <p>
                        <span><i class="fa fa-paperclip"></i> 1 dosya eki mevcut. </span>
                        <a target="_blank" href="~/uploads/@Model.Message.AttachmentUrl"> İndir/Aç </a>
                    </p>
                }
                else
                {
                    <p>
                        <span><i class="fa fa-paperclip"></i> Mesaj eki bulunmamaktadır. </span>
                    </p>
                }
            </div>
            <div class="compose-btn pull-left">
                <a asp-controller="Messages" asp-action="ComposeMessage" asp-route-id="@Model.User.Id" class="btn btn-sm btn-theme"><i class="fa fa-reply"></i> Yanıtla </a>
            </div>
        </div>
    </section>
</div>

LibraryProject/Views/Messages/Sent.cshtml
@model List<Message>
@{
    ViewData["Title"] = "Gönderidiğim Mesajlar";
    Layout = "~/Views/Shared/_LayoutMessages.cshtml";
}

<div class="col-sm-9">
    <section class="panel">
        <header class="panel-heading wht-bg">
            <h4 class="gen-case">
                Gönderilen Mesajlar
            </h4>
        </header>
        <div class="panel-body minimal">
            <div class="table-inbox-wrap ">
                <table class="table table-inbox table-hover">
                    <thead>
                        <tr>
                            <th style="width: 200px;">Kime</th>
                            <th style="width: 400px;">Başlık</th>
                            <th class="text-right">Gönderilme Tarihi</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var message in Model)
                        {
                        <tr class="">
                            <td style="width: 200px;" class="view-message dont-show">@message.Receiver.FirstName @message.Receiver.LastName</td>
                            <td style="width: 400px;" class="view-message view-message">@message.Title</td>
                            <td class="view-message text-right">@message.CreatedDate</td>
                            <td><a asp-controller="Messages" asp-action="MessageDetail" asp-route-id="@message.Id" class="btn btn-primary btn-xs" style="color: #fff;">Detaylar </a></td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</div>